imports:
  - $import subprocess
  - $from pathlib import Path
  - $import os
  - $import json

hive_config_file: ""
config_dict: "$json.load(open(@hive_config_file))"
task_id: ""

cmd:
  - "nnunet_run_preprocessing"
  - "--config-file"
  - "$str(Path(os.environ['ROOT_FOLDER']).joinpath(@config_dict['Experiment Name'], @config_dict['Experiment Name'] + '_results','Dataset' + str(@task_id) + '_' + @config_dict['Experiment Name'] + '.json'))"

preprocess:
  - '$print(@cmd)'
  - '$subprocess.run(@cmd)'
