apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-data-preparation.fullname" . }}
  labels:
  {{- include "k8s-data-preparation.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
  {{- include "k8s-data-preparation.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
    {{- include "k8s-data-preparation.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.dshm}}
        - name: dshm
          emptyDir:
            medium: Memory
        {{- end}}
        {{- range .Values.extraSecretVolumes }}
        - name: {{ .name | quote }}
          secret:
            secretName: {{ .secretName | quote }}
        {{- end}}
        {{- range .Values.extraHostVolumes }}
        - name: {{ .name | quote }}
          hostPath:
            path: {{ .hostPath | quote }}
        {{- end }}
        {{- range .Values.extraNFSVolumes }}
        - name: {{ .name | quote }}
          nfs:
            path: {{ .hostPath | quote }}
            server: {{ .server | quote }}
      {{- end }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.extraEnv }}
          env:
          {{- toYaml .Values.extraEnv | nindent 12 }}
          {{- end }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}

          {{- if .Values.extraVolumeMounts }}
          volumeMounts:
          {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
  {{- end }}

