version: "3.1"
services:
  phnn:
    image: "phnn"
    container_name: phnn-environment
    shm_size: 16g
    env_file: credentials.env
    ports:
      - "30022:22"
      - "30006:6006"
    volumes:
      - /home/simone/Documents/Projects/Hive:/home/Hive
      - /mnt/nfs_share/Data/LungLobeSeg:/home/LungLobeSeg
    deploy:
      resources:
        limits:
          cpus: '20.0'
          memory: 50G
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]