version: "3.1"
services:
  nnunet:
    image: "hive"
    container_name: hive-environment
    shm_size: 32g
    env_file: credentials.env
    ports:
      - "30022:22"
      - "30006:6006"
    volumes:
      - ${GIT_KEY_PATH}:/etc/secret-volume/ssh-privatekey
      - /e/GitHub/Hive:/home/Hive
      - /e/GitHub/nnUNet:/home/nnUNet
      - /c/Users/simon/LungLobeSeg:/home/LungLobeSeg/
    deploy:
      resources:
        limits:
          cpus: '10.0'
          memory: 32G
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]