apiVersion: v1
kind: Service
metadata:
  name: {{ include "nnunet-environment.fullname" . }}
  labels:
  {{- include "nnunet-environment.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type}}
  ports:
    {{- range .Values.service.ports}}
    - port: {{.port}}
      targetPort: {{.targetPort}}
      nodePort: {{.nodePort}}
      name: {{.name}}
  {{- end}}

  selector:
  {{- include "nnunet-environment.selectorLabels" . | nindent 4 }}