version: "3.1"
services:
  hive:
    image: "hive"
    container_name: hive-environment
    shm_size: 32g
    env_file: credentials.env
    ports:
      - "30024:22"
      - "30006:6006"
    volumes:
      - ../../:/home/Hive
      - ../../../nnUNet:/home/nnUNet
      - /c/Users/simon/LungLobeSeg:/home/LungLobeSeg/
    deploy:
      resources:
        limits:
          cpus: '10.0'
          memory: 16G
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]