version: "3.1"
services:
  nnunet:
    image: "nnunet"
    container_name: nnunet-environment
    shm_size: 32g
    env_file: credentials.env
    ports:
      - "30022:22"
      - "30006:6006"
    volumes:
      - /home/simone/Documents/Projects/Hive:/home/Hive
      - /home/simone/Documents/GitHub/nnUNet:/home/nnUNet
      - /mnt/nfs_share/Data/LungLobeSeg:/home/LungLobeSeg
    deploy:
      resources:
        limits:
          cpus: '10.0'
          memory: 32G
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]